spring:
  application:
    name: hiringApp
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    port: 8080

    spring:
      cloud:
        compatibility-verifier:
          enabled: false